# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.pepper
PackageVersion: 1.8.0
InstallerType: portable
Commands:
- cv4pve-pepper
ReleaseDate: 2024-08-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-pepper/releases/download/v1.8.0/cv4pve-pepper.exe-win-x64.zip
  InstallerSha256: 9359A91A6373B040A0A7C69FE1C5C6208691121B22BD6F0D67B241F74589F2C5
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cv4pve-pepper.exe
    PortableCommandAlias: cv4pve-pepper
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-pepper/releases/download/v1.8.0/cv4pve-pepper.exe-win-x86.zip
  InstallerSha256: 985F7F1D77F0B6064DF0DC036AAF7E81E779AAADE32587F838650E92F66CF6BF
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cv4pve-pepper.exe
    PortableCommandAlias: cv4pve-pepper
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-pepper/releases/download/v1.8.0/cv4pve-pepper.exe-win-arm64.zip
  InstallerSha256: 913C0AE671D5675C9DA801B9C0D41792EEF29213FE578EEB617F8F2F2AC885F9
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cv4pve-pepper.exe
    PortableCommandAlias: cv4pve-pepper
ManifestType: installer
ManifestVersion: 1.10.0
